disabled_rules:
  - trailing_comma
opt_in_rules:
  - anyobject_protocol
  - explicit_init
  - force_unwrapping
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_opening_braces
  - vertical_whitespace_closing_braces
excluded:
  - Pods
reporter: "xcode"
