source 'https://cdn.cocoapods.org/'

platform :ios, '13.0'

target 'TodoList' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TodoList

  target 'TodoListTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
